# Generated by Django 3.2.4 on 2021-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0003_auto_20210612_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='image/'),
            preserve_default=False,
        ),
    ]
