# Generated by Django 3.2.4 on 2021-06-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0006_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='create_data',
        ),
    ]
